require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CohortsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Cohort. As you add validations to Cohort, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CohortsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all cohorts as @cohorts" do
      cohort = Cohort.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:cohorts)).to eq([cohort])
    end
  end

  describe "GET #show" do
    it "assigns the requested cohort as @cohort" do
      cohort = Cohort.create! valid_attributes
      get :show, {:id => cohort.to_param}, valid_session
      expect(assigns(:cohort)).to eq(cohort)
    end
  end

  describe "GET #new" do
    it "assigns a new cohort as @cohort" do
      get :new, {}, valid_session
      expect(assigns(:cohort)).to be_a_new(Cohort)
    end
  end

  describe "GET #edit" do
    it "assigns the requested cohort as @cohort" do
      cohort = Cohort.create! valid_attributes
      get :edit, {:id => cohort.to_param}, valid_session
      expect(assigns(:cohort)).to eq(cohort)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Cohort" do
        expect {
          post :create, {:cohort => valid_attributes}, valid_session
        }.to change(Cohort, :count).by(1)
      end

      it "assigns a newly created cohort as @cohort" do
        post :create, {:cohort => valid_attributes}, valid_session
        expect(assigns(:cohort)).to be_a(Cohort)
        expect(assigns(:cohort)).to be_persisted
      end

      it "redirects to the created cohort" do
        post :create, {:cohort => valid_attributes}, valid_session
        expect(response).to redirect_to(Cohort.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved cohort as @cohort" do
        post :create, {:cohort => invalid_attributes}, valid_session
        expect(assigns(:cohort)).to be_a_new(Cohort)
      end

      it "re-renders the 'new' template" do
        post :create, {:cohort => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cohort" do
        cohort = Cohort.create! valid_attributes
        put :update, {:id => cohort.to_param, :cohort => new_attributes}, valid_session
        cohort.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested cohort as @cohort" do
        cohort = Cohort.create! valid_attributes
        put :update, {:id => cohort.to_param, :cohort => valid_attributes}, valid_session
        expect(assigns(:cohort)).to eq(cohort)
      end

      it "redirects to the cohort" do
        cohort = Cohort.create! valid_attributes
        put :update, {:id => cohort.to_param, :cohort => valid_attributes}, valid_session
        expect(response).to redirect_to(cohort)
      end
    end

    context "with invalid params" do
      it "assigns the cohort as @cohort" do
        cohort = Cohort.create! valid_attributes
        put :update, {:id => cohort.to_param, :cohort => invalid_attributes}, valid_session
        expect(assigns(:cohort)).to eq(cohort)
      end

      it "re-renders the 'edit' template" do
        cohort = Cohort.create! valid_attributes
        put :update, {:id => cohort.to_param, :cohort => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested cohort" do
      cohort = Cohort.create! valid_attributes
      expect {
        delete :destroy, {:id => cohort.to_param}, valid_session
      }.to change(Cohort, :count).by(-1)
    end

    it "redirects to the cohorts list" do
      cohort = Cohort.create! valid_attributes
      delete :destroy, {:id => cohort.to_param}, valid_session
      expect(response).to redirect_to(cohorts_url)
    end
  end

end
